#!/bin/bash
set -u
set -e
CLI_VERSION="0.1"

# Heqet Config
if [ -f Heqetfile ] ; then
  source Heqetfile
else
  echo "Error: Couldn't find Heqetfile in current working directory."
  exit 1
fi
HEQET_REPO="${heqet_repo:-https://github.com/nold360/heqet.git}"
HEQET_REVISION="${heqet_revision:-v3}"
HEQET_PATH="${heqet_path:-charts/heqet}"
USERDATA_REPO=$(pwd)
#USERDATA_REVISION=

HEQET_TMPDIR="${HEQET_TMPDIR:-/tmp/heqet}"

for cmd in helm git ; do
  if ! type $cmd &>/dev/null ; then
    echo "ERROR: Missing dependency: '$cmd'"
    exit 1
  fi
done

# Clone Heqet-Code & add current directory as userdata submodule
function setup {
  if [ ! -d ${HEQET_TMPDIR} ] ; then
		git clone -b ${HEQET_REVISION} ${HEQET_REPO} ${HEQET_TMPDIR}
		git -C ${HEQET_TMPDIR} submodule add ${USERDATA_REPO} ${HEQET_TMPDIR}/${HEQET_PATH}/userdata
    return $?
  else
    echo "Directory already exists! '$HEQET_TMPDIR'. Skipping setup"
    return 0
  fi
}

function update {
  if [ -d ${HEQET_TMPDIR}/.git ] ; then
  	git -C ${HEQET_TMPDIR} fetch --all -v --recurse-submodules &>/dev/null
    return $?
  else
    echo "ERROR: Directory '${HEQET_TMPDIR}' doesn't seem to be a git repo. Did you call 'hqt setup'?"
    return 1
  fi
}

function template {
  if [ -f ${HEQET_TMPDIR}/${HEQET_PATH}/Chart.yaml ] ; then
    helm template ${HEQET_TMPDIR}/${HEQET_PATH} --set userdata=userdata
    return $?
  else
    echo "ERROR: Couldn't find Chart.yaml in $HEQET_TMPDIR/${HEQET_PATH}. Did you call 'hqt setup'?"
    return 1
  fi
}

function help {
  echo "Usage: $0 <setup|update|template>"
  echo "Heqet-CLI v${CLI_VERSION} to setup heqet for helm templating."
  echo "Setup requires ENV-Variables 'USERDATA_REPO' & 'USERDATA_REVISION' of configuration git repo"
}

param="${1:-help}"
case $param in
  "setup") setup; exit $? ;;
  "update") update; exit $? ;;
  "template") template; exit $? ;;
  *) help; exit 0 ;;
esac
